services:
  bot123:
    build: .
    container_name: bot123
    restart: always
    network_mode: host
    ports:
      - "12366:12366"
    volumes:
      - /root/docker/db:/app/db
      - ./upload:/app/upload
      - ./transfer:/app/transfer
    environment:
      # 必填：代理配置（v2填20172带分流规则的端口，clash填7890端口）
      - HTTP_PROXY=http://192.168.31.63:7890
      # 必填：代理配置（v2填20172带分流规则的端口，clash填7890端口）
      - HTTPS_PROXY=http://192.168.31.63:7890
      # 必填：时区配置
      - TZ=Asia/Shanghai
      # 必填：TG机器人Token（从@BotFather获取）
      - ENV_TG_BOT_TOKEN=7773483990:AAE4dDZdml7IPmAmIw17OBkSWiu723YwnX0
      # 必填：TG管理员用户ID（从@userinfobot获取）
      - ENV_TG_ADMIN_USER_ID=7955100603
      # 必填：WEB配置页面的登录账号
      - ENV_WEB_PASSPORT=admin
      # 必填：WEB配置页面的登录密码
      - ENV_WEB_PASSWORD=dxw13145920
      # 代理配置，以下地址不走代理
      - NO_PROXY=localhost,127.0.0.1,192.168.0.0/16,10.0.0.0/8,*.123pan.com,*.115.com,*.189.cn,*.*.189.cn,*.quark.cn

